name: awkward-array-primer
channels:
  - conda-forge
dependencies:
  # Dev environment
  - python =3.10
  - jupyter_server
  - jupyterlab =4.0.6
  - jupyterlab-myst =2.1.0
  - pip:
      - jupyterlite-core >=0.2.0a0,<0.3.0
      - jupyterlite-xeus-python >=1.0.0a0,<2.0.0
      - ./extern/jupyterlab_deck-0.4.0a0-py3-none-any.whl
  # Kernel environment
  - awkward >=2.4.0
  - hist-base =2.7.2
  - vector =1.1.1.post1
  - numpy =1.25.2
  - matplotlib-base =3.5.2
  - mplhep =0.3.28
  - pyarrow
